/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffb596',
        'inverse-primary': '#adc7f7',
        'secondary-fixed': '#b1f0ce',
        'tertiary-container': '#612100',
        'primary-fixed': '#d6e3ff',
        'on-surface': '#191c1e',
        'secondary-fixed-dim': '#95d4b3',
        'error-container': '#ffdad6',
        'on-primary-container': '#86a0cd',
        'on-tertiary-fixed': '#360f00',
        'surface-container-low': '#f2f4f6',
        'outline-variant': '#c4c6cf',
        surface: '#f7f9fb',
        background: '#f7f9fb',
        'on-secondary-fixed-variant': '#0e5138',
        'tertiary-fixed': '#ffdbcd',
        error: '#ba1a1a',
        'surface-container-highest': '#e0e3e5',
        'surface-container': '#eceef0',
        primary: '#002045',
        'on-secondary': '#ffffff',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#455f88',
        'on-secondary-fixed': '#002114',
        tertiary: '#3e1200',
        'on-tertiary': '#ffffff',
        'inverse-on-surface': '#eff1f3',
        'on-background': '#191c1e',
        outline: '#74777f',
        'on-tertiary-container': '#f47d45',
        'on-primary-fixed': '#001b3c',
        'on-primary': '#ffffff',
        'surface-dim': '#d8dadc',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed-variant': '#7d2d00',
        'surface-bright': '#f7f9fb',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#adc7f7',
        'secondary-container': '#aeeecb',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8ea',
        secondary: '#2c694e',
        'primary-container': '#1a365d',
        'on-surface-variant': '#43474e',
        'on-secondary-container': '#316e52',
        'on-primary-fixed-variant': '#2d476f',
        'on-error': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
