/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f7f9fb',
        'surface-container-low': '#f2f4f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#d8dbde',
        'surface-container': '#ececef',
        primary: '#002045',
        'primary-container': '#1a365d',
        secondary: '#2c694e',
        tertiary: '#1e4d2b',
        error: '#ba1a1a',
        'on-surface': '#181c1e',
        'on-surface-variant': '#424750',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-background': '#181c1e',
        outline: '#737781',
        'outline-variant': '#c4c6cf',
        background: '#f7f9fb',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eef1f4',
        'inverse-primary': '#a8c8ff',
        'surface-dim': '#d7dadd',
        'surface-bright': '#f7f9fb',
        'surface-variant': '#e0e3e6',
        'surface-tint': '#2e5fa0',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#a8c8ff',
        'secondary-fixed': '#cae6ff',
        'secondary-fixed-dim': '#8ccdff',
        'tertiary-fixed': '#94f990',
        'tertiary-fixed-dim': '#78dc77',
        'tertiary-container': '#612100',
        'on-primary-container': '#84b0f7',
        'on-secondary-container': '#004a6d',
        'on-tertiary-container': '#61c462',
        'on-primary-fixed': '#001b3c',
        'on-primary-fixed-variant': '#0a4687',
        'on-secondary-fixed': '#001e2f',
        'on-secondary-fixed-variant': '#004b6f',
        'on-tertiary-fixed': '#002204',
        'on-tertiary-fixed-variant': '#005313',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.25rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
