COMMENT ON COLUMN "tfrshman_enrl_stts"."schl_knd_nm" IS '샘플: 대학교, 사이버대학(대학), 교육대학, 산업대학, 각종학교(대학) 등';
COMMENT ON COLUMN "tfrshman_enrl_stts"."fndn_dv_nm" IS '샘플: 사립, 국립, 특별법법인, 특별법국립, 공립 등';
COMMENT ON COLUMN "tfrshman_enrl_stts"."rgn_nm" IS '샘플: 서울, 경기, 경북, 충남, 부산 등';
COMMENT ON COLUMN "tfrshman_enrl_stts"."stts_nm" IS '샘플: 기존, 신설 등';
COMMENT ON COLUMN "tgradu_grade"."schl_knd_nm" IS '샘플: 대학교, 사이버대학(대학), 교육대학, 산업대학, 각종학교(대학) 등';
COMMENT ON COLUMN "tgradu_grade"."fndn_dv_nm" IS '샘플: 사립, 국립, 특별법법인, 국립대법인, 특별법국립 등';
COMMENT ON COLUMN "tgradu_grade"."rgn_nm" IS '샘플: 서울, 경기, 경북, 충남, 부산 등';
COMMENT ON COLUMN "tgradu_grade"."stts_nm" IS '샘플: 기존, 폐교 등';
COMMENT ON COLUMN "tfultm_adm_oficr"."schl_knd_nm" IS '샘플: 대학교, 교육대학, 산업대학, 사이버대학(대학) 등';
COMMENT ON COLUMN "tfultm_adm_oficr"."fndn_dv_nm" IS '샘플: 사립, 국립, 특별법법인, 국립대법인, 공립 등';
COMMENT ON COLUMN "tfultm_adm_oficr"."rgn_nm" IS '샘플: 서울, 경기, 경북, 충남, 부산 등';
COMMENT ON COLUMN "tfultm_adm_oficr"."stts_nm" IS '샘플: 기존, 신설, 폐교 등';
COMMENT ON COLUMN "tq_overview_text_block"."screen_code" IS '샘플: overview 등';
COMMENT ON COLUMN "tq_overview_text_block"."block_code" IS '샘플: HEADER_CONTEXT, SAMPLE_INSIGHT, SUMMARY_JUDGMENT 등';
COMMENT ON COLUMN "tq_overview_text_block"."block_area_name" IS '샘플: 좌상단 텍스트, 우상단 종합판정, 좌하단 샘플인사이트 등';
COMMENT ON COLUMN "tq_overview_text_line"."screen_code" IS '샘플: overview 등';
COMMENT ON COLUMN "tq_overview_text_line"."block_code" IS '샘플: SAMPLE_INSIGHT, HEADER_CONTEXT, SUMMARY_JUDGMENT 등';
COMMENT ON COLUMN "tadm_tp_sel_rslt"."schl_knd_nm" IS '샘플: 대학교, 사이버대학(대학), 교육대학, 산업대학, 방송통신대학 등';
COMMENT ON COLUMN "tadm_tp_sel_rslt"."fndn_dv_nm" IS '샘플: 사립, 국립, 특별법법인, 국립대법인, 공립 등';
COMMENT ON COLUMN "tadm_tp_sel_rslt"."rgn_nm" IS '샘플: 서울, 경기, 충남, 경북, 부산 등';
COMMENT ON COLUMN "tadm_tp_sel_rslt"."stts_nm" IS '샘플: 기존, 폐교, 신설 등';
COMMENT ON COLUMN "tadm_tp_sel_rslt"."capa_dv_nm" IS '샘플: 정원내, 정원외 등';
COMMENT ON COLUMN "tadm_tp_sel_rslt"."sel_tp_nm" IS '샘플: 학생부위주(교과), 수능위주, 기타, 학생부위주(종합), 실기위주 등';
COMMENT ON COLUMN "tadm_tp_sel_rslt"."sel_lcl1_nm" IS '샘플: 사회통합전형(기회균형)(정원외), 일반전형, 재외국민 외국인(정원외), 대학별독자적기준, 지역인재 특별전형 등';
COMMENT ON COLUMN "tq_overview_detail_grid"."screen_code" IS '샘플: overview 등';
COMMENT ON COLUMN "tq_overview_detail_grid"."metric_code" IS '샘플: M08_DORM_OCCUPANCY, M09_RESEARCH_FUND_PER_FACULTY, M10_TECH_TRANSFER_INCOME, M06_EDU_COST_PER_STUDENT, M03_EMPLOYMENT 등';
COMMENT ON COLUMN "tq_overview_detail_grid"."metric_name" IS '샘플: 취업률, 전임교원 1인당 연구비, 기숙사 수용률, 학생 1인당 교육비, 재학생 1인당 장학금 등';
COMMENT ON COLUMN "tq_overview_detail_grid"."metric_unit_code" IS '샘플: PERCENT, KRW_PER_STUDENT, THOUSAND_KRW_PER_FACULTY, KRW 등';
COMMENT ON COLUMN "tq_overview_detail_grid"."metric_unit_name" IS '샘플: %, 원/인, 원, 천원/인 등';
COMMENT ON COLUMN "tq_overview_detail_grid"."source_table_name" IS '샘플: t_grdts_emplmt, t_grdts_fur_edu, t_national_public_univ_corp_spcl_law / t_per_stdnt_edu_expns_private, t_tech_trans_incm_cntrt_perf, t_rsrch_fund_bnfc_perf 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."screen_code" IS '샘플: overview 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."metric_code" IS '샘플: M02_DROPOUT, M08_DORM_OCCUPANCY, M03_EMPLOYMENT, M04_ADVANCE, M01_FRESHMAN_FILL 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."metric_name" IS '샘플: 진학률, 기숙사, 교원확보, 중도탈락, 취업률 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."x_unit_code" IS '샘플: PERCENT_POINT 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."y_unit_code" IS '샘플: PERCENT_POINT 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."comparison_direction_code" IS '샘플: HIGHER_BETTER, LOWER_BETTER 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."quadrant_code" IS '샘플: FOCUS_PROMOTION, PRIORITY_IMPROVEMENT, NO_DATA, NATIONAL_WEAKNESS, REGIONAL_WEAKNESS 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."quadrant_name" IS '샘플: 집중 홍보 구간, 우선 개선 구간, 데이터 없음, 전국 열세 개선, 지역 열세 개선 등';
COMMENT ON COLUMN "tq_overview_matrix_point"."source_metric_code" IS '샘플: M02_DROPOUT, M08_DORM_OCCUPANCY, M03_EMPLOYMENT, M04_ADVANCE, M01_FRESHMAN_FILL 등';
COMMENT ON COLUMN "tq_overview_metric_card"."screen_code" IS '샘플: overview 등';
COMMENT ON COLUMN "tq_overview_metric_card"."metric_code" IS '샘플: M08_DORM_OCCUPANCY, M09_RESEARCH_FUND_PER_FACULTY, M10_TECH_TRANSFER_INCOME, M06_EDU_COST_PER_STUDENT, M03_EMPLOYMENT 등';
COMMENT ON COLUMN "tq_overview_metric_card"."metric_name" IS '샘플: 취업률, 전임교원 1인당 연구비, 기숙사 수용률, 학생 1인당 교육비, 재학생 1인당 장학금 등';
COMMENT ON COLUMN "tq_overview_metric_card"."metric_unit_code" IS '샘플: PERCENT, KRW_PER_STUDENT, THOUSAND_KRW_PER_FACULTY, KRW 등';
COMMENT ON COLUMN "tq_overview_metric_card"."metric_unit_name" IS '샘플: %, 원/인, 원, 천원/인 등';
COMMENT ON COLUMN "tq_overview_metric_card"."comparison_direction_code" IS '샘플: HIGHER_BETTER, LOWER_BETTER 등';
COMMENT ON COLUMN "tq_overview_metric_card"."source_table_name" IS '샘플: t_grdts_emplmt, t_grdts_fur_edu, t_tech_trans_incm_cntrt_perf, t_national_public_univ_corp_spcl_law / t_per_stdnt_edu_expns_private, t_rsrch_fund_bnfc_perf 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."screen_code" IS '샘플: overview 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."metric_code" IS '샘플: M08_DORM_OCCUPANCY, M09_RESEARCH_FUND_PER_FACULTY, M10_TECH_TRANSFER_INCOME, M06_EDU_COST_PER_STUDENT, M03_EMPLOYMENT 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."metric_name" IS '샘플: 취업률, 전임교원 1인당 연구비, 기숙사 수용률, 학생 1인당 교육비, 재학생 1인당 장학금 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."comparison_direction_code" IS '샘플: HIGHER_BETTER, LOWER_BETTER 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."region_unit_code" IS '샘플: PERCENT_POINT, KRW, THOUSAND_KRW_PER_FACULTY 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."region_status_code" IS '샘플: NEEDS_ATTENTION, ADVANTAGE, MIXED, NO_DATA 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."region_status_name" IS '샘플: 보완필요, 우위, 혼재, 미공시 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."national_unit_code" IS '샘플: PERCENT_POINT, KRW, THOUSAND_KRW_PER_FACULTY 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."national_status_code" IS '샘플: NEEDS_ATTENTION, ADVANTAGE, NO_DATA, MIXED 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."national_status_name" IS '샘플: 보완필요, 우위, 미공시, 혼재 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."judgment_status_code" IS '샘플: MIXED, NEEDS_ATTENTION, ADVANTAGE, NO_DATA 등';
COMMENT ON COLUMN "tq_overview_risk_analysis"."judgment_status_name" IS '샘플: 혼재, 보완필요, 우위, 미공시 등';
COMMENT ON COLUMN "tq_screen_chart_block"."screen_code" IS '샘플: finance, research, education, campus, admission 등';
COMMENT ON COLUMN "tq_screen_chart_block"."screen_name" IS '샘플: 학생/진로, 연구/산학/창업, 재정/등록금/학생지원, 거버넌스/인증/컴플라이언스, 교육/교원 등';
COMMENT ON COLUMN "tq_screen_chart_block"."block_code" IS '샘플: CHART_LEFT, CHART_RIGHT 등';
COMMENT ON COLUMN "tq_screen_detail_grid"."screen_code" IS '샘플: admission, campus, education, finance, governance 등';
COMMENT ON COLUMN "tq_screen_detail_grid"."screen_name" IS '샘플: 학생/진로, 연구/산학/창업, 재정/등록금/학생지원, 거버넌스/인증/컴플라이언스, 교육/교원 등';
COMMENT ON COLUMN "tq_screen_detail_grid"."comparison_direction_code" IS '샘플: HIGHER_BETTER, LOWER_BETTER 등';
COMMENT ON COLUMN "tq_screen_metric_card"."screen_code" IS '샘플: admission, campus, education, finance, governance 등';
COMMENT ON COLUMN "tq_screen_metric_card"."screen_name" IS '샘플: 학생/진로, 연구/산학/창업, 재정/등록금/학생지원, 거버넌스/인증/컴플라이언스, 교육/교원 등';
COMMENT ON COLUMN "tq_screen_metric_card"."comparison_direction_code" IS '샘플: HIGHER_BETTER, LOWER_BETTER 등';
COMMENT ON COLUMN "tq_screen_source_ref"."screen_code" IS '샘플: campus, admission, research, finance, student 등';
COMMENT ON COLUMN "tq_screen_source_ref"."screen_name" IS '샘플: 입학/선발, 캠퍼스/복지/안전, 연구/산학/창업, 재정/등록금/학생지원, 학생/진로 등';
COMMENT ON COLUMN "tq_screen_text_block"."screen_code" IS '샘플: finance, research, education, campus, admission 등';
COMMENT ON COLUMN "tq_screen_text_block"."screen_name" IS '샘플: 학생/진로, 연구/산학/창업, 재정/등록금/학생지원, 거버넌스/인증/컴플라이언스, 교육/교원 등';
COMMENT ON COLUMN "tq_screen_text_block"."block_code" IS '샘플: PANEL_SUMMARY, HEADER_CONTEXT, SAMPLE_INSIGHT 등';
COMMENT ON COLUMN "tq_screen_text_block"."block_area_name" IS '샘플: 좌상단 텍스트, 우상단 요약, 좌하단 인사이트 등';
COMMENT ON COLUMN "tq_screen_text_line"."screen_code" IS '샘플: finance, research, education, campus, admission 등';
COMMENT ON COLUMN "tq_screen_text_line"."screen_name" IS '샘플: 학생/진로, 연구/산학/창업, 재정/등록금/학생지원, 거버넌스/인증/컴플라이언스, 교육/교원 등';
COMMENT ON COLUMN "tq_screen_text_line"."block_code" IS '샘플: SAMPLE_INSIGHT, PANEL_SUMMARY, HEADER_CONTEXT 등';
COMMENT ON COLUMN "ts_univ_info"."prov_cd" IS '샘플: 11, 41, 47, 51, 26 등';
COMMENT ON COLUMN "ts_univ_info"."prov_nm" IS '샘플: 서울특별시, 경기도, 경상북도, 부산광역시, 강원특별자치도 등';
COMMENT ON COLUMN "tq_screen_chart_item"."screen_code" IS '샘플: admission, research, student, campus, education 등';
COMMENT ON COLUMN "tq_screen_chart_item"."screen_name" IS '샘플: 입학/선발, 연구/산학/창업, 학생/진로, 캠퍼스/복지/안전, 교육/교원 등';
COMMENT ON COLUMN "tq_screen_chart_item"."block_code" IS '샘플: CHART_LEFT, CHART_RIGHT 등';
COMMENT ON COLUMN "tq_screen_chart_item"."bar_scale_type_code" IS '샘플: RELATIVE_TO_MAX, PERCENT_VALUE, TEXT_ONLY, PERCENT_OF_TOTAL 등';
COMMENT ON COLUMN "ts_user_info"."user_nm" IS '샘플: 오충남, 오전북, 오부산, 오서울, 오부경 등';
COMMENT ON COLUMN "ts_user_info"."auth_grp_cd" IS '샘플: 10 등';
COMMENT ON COLUMN "ts_user_info"."mobile_co_cd" IS '샘플: 10 등';
COMMENT ON COLUMN "ts_user_info"."univ_cd" IS '샘플: 0083000, 0050000, 0002000, 0081000, 0093000 등';
COMMENT ON COLUMN "tx_ir_metric_def"."domain_cd" IS '샘플: D06, D03, D07, D01, D04 등';
COMMENT ON COLUMN "tx_ir_metric_def"."domain_nm" IS '샘플: 재정/회계/건전성, 졸업/취업/진학 성과, 연구/산학/창업, 교원/교육여건, 입학/충원 등';
COMMENT ON COLUMN "ts_grp_info"."grp_cd" IS '샘플: STDNT, EMP, GRDNT, PROF 등';
COMMENT ON COLUMN "ts_grp_info"."grp_nm" IS '샘플: 교수, 교직원, 학생(대학원), 학생(학부) 등';
COMMENT ON COLUMN "tx_dcsn_run_mst"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_run_mst"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_dcsn_run_mst"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_dcsn_run_mst"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_dcsn_run_mst"."scenario_code" IS '샘플: BASE 등';
COMMENT ON COLUMN "tx_dcsn_run_mst"."calc_status_code" IS '샘플: READY 등';
COMMENT ON COLUMN "tx_dcsn_text_result"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_text_result"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_dcsn_text_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_dcsn_text_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_dcsn_text_result"."block_code" IS '샘플: OBJECTIVE, GENERATED_INFO, PREDICTION, MANAGEMENT 등';
COMMENT ON COLUMN "tx_dcsn_text_result"."block_area_name" IS '샘플: HEADER, CENTER, RIGHT, BOTTOM 등';
COMMENT ON COLUMN "tx_dcsn_text_result"."line_role_code" IS '샘플: SUMMARY, ACTION, INTERPRET 등';
COMMENT ON COLUMN "tx_dcsn_text_result"."tone_code" IS '샘플: NEUTRAL 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."metric_code" IS '샘플: _______, _________, ___________, ____1______, _____ 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."metric_unit_code" IS '샘플: money, percent, count 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."compare_group_code" IS '샘플: REGION_AVG, NATIONAL_AVG, SELF 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."compare_group_nm" IS '샘플: 우리 대학, 동일지역 평균, 전국 평균 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."direction_code" IS '샘플: STABLE 등';
COMMENT ON COLUMN "tx_dcsn_metric_result"."status_code" IS '샘플: DESIGN 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."screen_code" IS '샘플: decision_investment, decision_risk, decision_cash, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."block_code" IS '샘플: COMPARE_MAIN, TREND_MAIN 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."chart_code" IS '샘플: CHART_COMPARE, CHART_TREND 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."chart_type_code" IS '샘플: BAR_H, BAR_V 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."chart_style_code" IS '샘플: compare, trend 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."series_code" IS '샘플: TREND, REGION_AVG, NATIONAL_AVG, SELF 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."series_name" IS '샘플: 비교군, 최근 3개년 등';
COMMENT ON COLUMN "tx_dcsn_chart_result"."bar_scale_type_code" IS '샘플: RELATIVE_TO_MAX 등';
COMMENT ON COLUMN "tx_dcsn_grid_result"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_grid_result"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_dcsn_grid_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_dcsn_grid_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_dcsn_grid_result"."grid_code" IS '샘플: GRID_MAIN 등';
COMMENT ON COLUMN "tx_dcsn_grid_result"."metric_code" IS '샘플: _______, _________, ___________, ____1______, _____ 등';
COMMENT ON COLUMN "tx_dcsn_grid_result"."metric_unit_code" IS '샘플: money, percent, count 등';
COMMENT ON COLUMN "tx_dcsn_grid_result"."judgment_code" IS '샘플: ADVANTAGE, WEAKNESS, NO_DATA, MIXED 등';
COMMENT ON COLUMN "tx_dcsn_source_ref"."screen_code" IS '샘플: decision_revenue, decision_cost, decision_risk, decision_cash, decision_investment 등';
COMMENT ON COLUMN "tx_dcsn_source_ref"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_dcsn_source_ref"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_dcsn_run_mst_desc"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_run_mst_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_dcsn_text_result_desc"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_text_result_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_dcsn_text_result_desc"."block_code" IS '샘플: OBJECTIVE 등';
COMMENT ON COLUMN "tx_dcsn_text_result_desc"."line_role_code" IS '샘플: SUMMARY 등';
COMMENT ON COLUMN "tx_dcsn_metric_result_desc"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_metric_result_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_dcsn_metric_result_desc"."metric_code" IS '샘플: MTR_MAIN 등';
COMMENT ON COLUMN "tx_dcsn_chart_result_desc"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_chart_result_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_dcsn_chart_result_desc"."block_code" IS '샘플: COMPARE_MAIN 등';
COMMENT ON COLUMN "tx_dcsn_chart_result_desc"."chart_code" IS '샘플: CHART_MAIN 등';
COMMENT ON COLUMN "tx_dcsn_chart_result_desc"."series_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_dcsn_grid_result_desc"."screen_code" IS '샘플: decision_risk, decision_cash, decision_investment, decision_cost, decision_revenue 등';
COMMENT ON COLUMN "tx_dcsn_grid_result_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_dcsn_grid_result_desc"."grid_code" IS '샘플: GRID_MAIN 등';
COMMENT ON COLUMN "tx_dcsn_source_ref_desc"."screen_code" IS '샘플: decision_revenue, decision_cost, decision_risk, decision_cash, decision_investment 등';
COMMENT ON COLUMN "tx_dcsn_source_ref_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."acct_div_code" IS '샘플: OPER 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."acct_l1_code" IS '샘플: REV 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."acct_l1_nm" IS '샘플: 수입 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."acct_l2_code" IS '샘플: TTN 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."acct_l2_nm" IS '샘플: 등록금 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."acct_l3_code" IS '샘플: TTN_MAIN 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."acct_l3_nm" IS '샘플: 등록금수입 등';
COMMENT ON COLUMN "tx_fcst_monthly_exec_input"."inout_code" IS '샘플: IN 등';
COMMENT ON COLUMN "tx_fcst_dept_metric_input"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_fcst_dept_metric_input"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_fcst_dept_metric_input"."campus_nm" IS '샘플: 본교 등';
COMMENT ON COLUMN "tx_fcst_dept_metric_input"."college_nm" IS '샘플: 공과대학 등';
COMMENT ON COLUMN "tx_fcst_dept_metric_input"."dept_cd" IS '샘플: D001 등';
COMMENT ON COLUMN "tx_fcst_dept_metric_input"."dept_nm" IS '샘플: 샘플학과 등';
COMMENT ON COLUMN "tx_fcst_feature_store"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_fcst_feature_store"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_fcst_feature_store"."feature_group_code" IS '샘플: ADM, EMP, FIN 등';
COMMENT ON COLUMN "tx_fcst_feature_store"."feature_code" IS '샘플: TUITION_DEP, EMPL_RATE, FILL_RATE 등';
COMMENT ON COLUMN "tx_fcst_feature_store"."feature_name" IS '샘플: 등록금 의존도, 정원내 신입생 충원율, 취업률 등';
COMMENT ON COLUMN "tx_fcst_feature_store"."feature_unit_code" IS '샘플: MIXED 등';
COMMENT ON COLUMN "tx_fcst_feature_store"."source_table_name" IS '샘플: 문서 기반 설계 등';
COMMENT ON COLUMN "tx_fcst_scenario"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_fcst_scenario"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_fcst_scenario"."scenario_code" IS '샘플: BASE 등';
COMMENT ON COLUMN "tx_fcst_scenario"."scenario_name" IS '샘플: 기본 시나리오 등';
COMMENT ON COLUMN "tx_fcst_run_mst"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_fcst_run_mst"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_fcst_run_mst"."scenario_code" IS '샘플: BASE 등';
COMMENT ON COLUMN "tx_fcst_run_mst"."model_code" IS '샘플: RULE_BASED 등';
COMMENT ON COLUMN "tx_fcst_run_mst"."run_status_code" IS '샘플: READY 등';
COMMENT ON COLUMN "t_cntrt_dept_quota_sys_inst_opr"."expns_sup_ext_org_nm" IS '샘플: 중소벤처기업부, 고용노동부, 교육부, 한국장학재단, 경산시, 경상북도, 전라남도, 목포시, 나주시, 무안군, 영암군, 교육부 등';
COMMENT ON COLUMN "tx_fcst_result"."analysis_code" IS '샘플: RISK_049 등';
COMMENT ON COLUMN "tx_fcst_result"."screen_code" IS '샘플: decision_risk 등';
COMMENT ON COLUMN "tx_fcst_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_fcst_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_fcst_result"."metric_code" IS '샘플: OPER_MARGIN, TUITION_INCOME, FILL_RATE 등';
COMMENT ON COLUMN "tx_fcst_result"."metric_name" IS '샘플: 운영차액, 정원내 신입생 충원율, 등록금 수입 등';
COMMENT ON COLUMN "tx_fcst_result"."predict_group_code" IS '샘플: FORECAST_BASE 등';
COMMENT ON COLUMN "tx_fcst_result_desc"."analysis_code" IS '샘플: RISK_049 등';
COMMENT ON COLUMN "tx_fcst_result_desc"."metric_code" IS '샘플: OPER_MARGIN, TUITION_INCOME, FILL_RATE 등';
COMMENT ON COLUMN "tx_fcst_result_desc"."model_code" IS '샘플: RULE_BASED 등';
COMMENT ON COLUMN "tx_rel_run_mst"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_campus, rel_accounting 등';
COMMENT ON COLUMN "tx_rel_run_mst"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_rel_run_mst"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_rel_run_mst"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_rel_run_mst"."scenario_code" IS '샘플: BASE 등';
COMMENT ON COLUMN "tx_rel_run_mst"."calc_status_code" IS '샘플: READY 등';
COMMENT ON COLUMN "tx_rel_text_result"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_campus, rel_accounting 등';
COMMENT ON COLUMN "tx_rel_text_result"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_rel_text_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_rel_text_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_rel_text_result"."block_code" IS '샘플: SOURCES, OBJECTIVE, METRIC 등';
COMMENT ON COLUMN "tx_rel_text_result"."block_area_name" IS '샘플: LEFT 등';
COMMENT ON COLUMN "tx_rel_text_result"."line_role_code" IS '샘플: SUMMARY 등';
COMMENT ON COLUMN "tx_rel_text_result"."tone_code" IS '샘플: NEUTRAL 등';
COMMENT ON COLUMN "tx_rel_metric_result"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_accounting, rel_campus 등';
COMMENT ON COLUMN "tx_rel_metric_result"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_rel_metric_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_rel_metric_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_rel_metric_result"."metric_code" IS '샘플: REP_METRIC 등';
COMMENT ON COLUMN "tx_rel_metric_result"."metric_unit_code" IS '샘플: MIXED, count, percent, value 등';
COMMENT ON COLUMN "tx_rel_metric_result"."compare_group_code" IS '샘플: SELF, NATIONAL 등';
COMMENT ON COLUMN "tx_rel_metric_result"."compare_group_nm" IS '샘플: 우리 대학, 전국 평균 등';
COMMENT ON COLUMN "tx_rel_metric_result"."direction_code" IS '샘플: STABLE, UP, DOWN 등';
COMMENT ON COLUMN "tx_rel_metric_result"."status_code" IS '샘플: DESIGN, ADVANTAGE, MIXED, WEAKNESS 등';
COMMENT ON COLUMN "tx_rel_chart_result"."screen_code" IS '샘플: rel_governance, rel_campus, rel_student_outcome, rel_accounting, rel_research 등';
COMMENT ON COLUMN "tx_rel_chart_result"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_rel_chart_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_rel_chart_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_rel_chart_result"."block_code" IS '샘플: COMPARE_MAIN, TREND_MAIN 등';
COMMENT ON COLUMN "tx_rel_chart_result"."chart_code" IS '샘플: CHART_MAIN, CHART_TREND 등';
COMMENT ON COLUMN "tx_rel_chart_result"."chart_type_code" IS '샘플: BAR_H, BAR_V 등';
COMMENT ON COLUMN "tx_rel_chart_result"."chart_style_code" IS '샘플: comparison, trend 등';
COMMENT ON COLUMN "tx_rel_chart_result"."series_code" IS '샘플: SERIES_TREND, SERIES_COMPARE, SERIES_MAIN 등';
COMMENT ON COLUMN "tx_rel_chart_result"."series_name" IS '샘플: 비교군, 최근3개년 등';
COMMENT ON COLUMN "tx_rel_chart_result"."bar_scale_type_code" IS '샘플: PERCENT, TEXT_ONLY 등';
COMMENT ON COLUMN "tx_rel_grid_result"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_accounting, rel_campus 등';
COMMENT ON COLUMN "tx_rel_grid_result"."priority_code" IS '샘플: P2, P1, P3 등';
COMMENT ON COLUMN "tx_rel_grid_result"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_rel_grid_result"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_rel_grid_result"."grid_code" IS '샘플: GRID_MAIN 등';
COMMENT ON COLUMN "tx_rel_grid_result"."metric_code" IS '샘플: REP_METRIC 등';
COMMENT ON COLUMN "tx_rel_grid_result"."metric_unit_code" IS '샘플: MIXED, count, percent, value 등';
COMMENT ON COLUMN "tx_rel_grid_result"."judgment_code" IS '샘플: DESIGN, ADVANTAGE, MIXED, WEAKNESS 등';
COMMENT ON COLUMN "tx_rel_source_ref"."screen_code" IS '샘플: rel_accounting, rel_governance, rel_campus, rel_finance, rel_research 등';
COMMENT ON COLUMN "tx_rel_source_ref"."univ_cd" IS '샘플: 0093000 등';
COMMENT ON COLUMN "tx_rel_source_ref"."schl_nm" IS '샘플: 충남대학교 등';
COMMENT ON COLUMN "tx_rel_run_mst_desc"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_campus, rel_accounting 등';
COMMENT ON COLUMN "tx_rel_run_mst_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_rel_text_result_desc"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_campus, rel_accounting 등';
COMMENT ON COLUMN "tx_rel_text_result_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_rel_text_result_desc"."block_code" IS '샘플: OBJECTIVE 등';
COMMENT ON COLUMN "tx_rel_text_result_desc"."line_role_code" IS '샘플: SUMMARY 등';
COMMENT ON COLUMN "tx_rel_metric_result_desc"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_campus, rel_accounting 등';
COMMENT ON COLUMN "tx_rel_metric_result_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_rel_metric_result_desc"."metric_code" IS '샘플: REP_METRIC 등';
COMMENT ON COLUMN "tx_rel_chart_result_desc"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_campus, rel_accounting 등';
COMMENT ON COLUMN "tx_rel_chart_result_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_rel_chart_result_desc"."block_code" IS '샘플: COMPARE_MAIN 등';
COMMENT ON COLUMN "tx_rel_chart_result_desc"."chart_code" IS '샘플: CHART_MAIN 등';
COMMENT ON COLUMN "tx_rel_chart_result_desc"."series_code" IS '샘플: SERIES_MAIN 등';
COMMENT ON COLUMN "tx_rel_grid_result_desc"."screen_code" IS '샘플: rel_admission, rel_finance, rel_student_outcome, rel_campus, rel_accounting 등';
COMMENT ON COLUMN "tx_rel_grid_result_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "tx_rel_grid_result_desc"."grid_code" IS '샘플: GRID_MAIN 등';
COMMENT ON COLUMN "tx_rel_source_ref_desc"."screen_code" IS '샘플: rel_accounting, rel_governance, rel_campus, rel_finance, rel_research 등';
COMMENT ON COLUMN "tx_rel_source_ref_desc"."compare_group_std_code" IS '샘플: SELF 등';
COMMENT ON COLUMN "t_stdnt_cnt_scrn_rt_cyber_univ"."schl_nm" IS '샘플: 부산디지털대학교, 서울사이버대학교, 서울디지털대학교, 대구사이버대학교, 세종사이버대학교 등';
COMMENT ON COLUMN "t_stdnt_cnt_scrn_rt_cyber_univ"."univ_cd" IS '샘플: 0203000, 0195000, 0221000, 0184000, 0180000 등';
COMMENT ON COLUMN "t_ondemand_base_prog_inst_opr"."expns_sup_ext_org_nm" IS '샘플: 산업통상자원부, (재)전북테크노파크, 전북테크노파크, 교육부, 전라남도청, 전남인재육성재단 등';
COMMENT ON COLUMN "t_ondemand_base_prog_inst_opr"."expns_sup_ext_org_biz_nm" IS '샘플: 창의융합형공학인재양성지원사업, 대학혁신지원사업, 지역특성화산업 전문인력양성사업(취업연계형 특성화과정), 지역특성화산업 전문인력양성사업, 산학협력 취업패키지 등';